#!/usr/bin/env python3
"""
build_memory_index.py — MEMORY.md as a DERIVED VIEW, not a hand-maintained file.

WHY. MEMORY.md is the always-loaded page, and it has a hard read ceiling (past
roughly 24KB an agent silently truncates it). A hand-written index keeps hitting
that ceiling and gets shaved by hand, and every shave is a chance to lose a
pointer. But the page is NOT the retrieval path: the recall hook surfaces any
memory per prompt whether or not it is on the page. So the ceiling is on the
VIEW, not the corpus, and nothing has to be archived for the page to fit.
Eviction is the wrong lever; selection is the right one, and selection can be
computed from data the system already has.

HOW. Rank every active memory by behavioural signal:

    score   = recalls_30d * recency + 5 * link_in_degree
    recency = 1.0 if recalled in the last 7 days, 0.7 within 30, 0.4 otherwise

recalls_30d comes from recall_log.db, which memory_recall.py writes on every
prompt (every hit the hook injects is one row). link_in_degree is how many
other memory files [[link]] to it: other memories vouching for it. A memory
written in the last INDEX_NEWBORN_DAYS has no history yet and gets a floor,
so it spends a week on the page before the data decides. Memories whose
frontmatter `type:` is in INDEX_PIN_TYPES (default: feedback, the rules of
engagement) are pinned first regardless of score, and so is any file with
`pin: true`. Then the page is filled greedily from the top until the byte
budget is reached, and it stops. What did not fit is listed by name below
the fold, so a session still knows those memories exist and can go look.

The line for each memory is its frontmatter `hook:` (the few words a fresh
session needs to recognise it), falling back to `description`, then `name`.
To improve a line, edit that field in the memory; never the page.

USAGE
  build_memory_index.py            dry run: writes <cache>/memory-index-preview.md, prints stats
  build_memory_index.py --apply    backs up MEMORY.md to memory/archive/MEMORY.md.<ts>, overwrites it
Run it from a weekly timer and at the end of every consolidation pass. Set
MEMORY_OS to operate on another store (see config.py).
"""
from __future__ import annotations

import re
import sqlite3
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as cfg  # noqa: E402 — the path insert must precede this import

MEM = cfg.memory_dir()
RECALL_LOG = cfg.cache_dir() / "recall_log.db"
BUDGET = cfg.INDEX_BUDGET_BYTES
HOOK_LEN = cfg.INDEX_HOOK_LEN
PIN_TYPES = set(cfg.INDEX_PIN_TYPES)
TRAILER_RESERVE = cfg.INDEX_TRAILER_RESERVE   # the below-the-fold list counts against the budget too
NEWBORN_S = cfg.INDEX_NEWBORN_DAYS * 86400
NEWBORN_FLOOR = cfg.INDEX_NEWBORN_FLOOR
APPLY = "--apply" in sys.argv

HEADER = (
    "*DERIVED VIEW — do not hand-edit. Regenerated by .claude/hooks/build_memory_index.py*\n"
    "*(30d recall × recency + link in-degree; every {pins} memory pinned; budget {b:,}B).*\n"
    "*Memories below the fold are still retrieved per-prompt by the recall hook —*\n"
    "*this file is only what is ALWAYS loaded. To fix a line, add `hook:` to that memory.*\n\n"
)


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    out = {}
    for ln in text[3:end].splitlines():
        m = re.match(r"^\s*([\w-]+):\s*(.*)$", ln)
        if m:
            out[m.group(1)] = m.group(2).strip().strip('"')
    return out


def main() -> None:
    files = sorted(p for p in MEM.glob("*.md") if p.name != "MEMORY.md")
    if not files:
        print(f"no memories under {MEM}; nothing to derive")
        return
    meta = {p.stem: frontmatter(p) for p in files}
    now = time.time()

    # behavioural signal 1: what recall actually handed to sessions, last 30 days
    recalls, last_seen = {}, {}
    if RECALL_LOG.is_file():
        db = sqlite3.connect(str(RECALL_LOG))
        mem_resolved = MEM.resolve()
        for path, count, latest in db.execute(
                "SELECT path, COUNT(*), MAX(ts) FROM recalls WHERE ts>? GROUP BY path",
                (int(now - 30 * 86400),)):
            p = Path(path)
            if p.parent.resolve() == mem_resolved:
                recalls[p.stem], last_seen[p.stem] = count, latest
        db.close()

    # behavioural signal 2: inbound wikilinks from other memories
    indeg = {s: 0 for s in meta}
    for p in files:
        body = p.read_text(encoding="utf-8", errors="ignore")
        for target in set(re.findall(r"\[\[([\w-]+)", body)):
            if target in indeg and target != p.stem:
                indeg[target] += 1

    mtime = {p.stem: p.stat().st_mtime for p in files}

    def score(stem: str) -> float:
        age = now - last_seen.get(stem, 0)
        recency = 1.0 if age < 7 * 86400 else 0.7 if age < 30 * 86400 else 0.4
        base = recalls.get(stem, 0) * recency + 5 * indeg[stem]
        if now - mtime[stem] < NEWBORN_S:
            base = max(base, NEWBORN_FLOOR)
        return base

    pinned = [s for s in meta
              if str(meta[s].get("pin", "")).lower() == "true" or meta[s].get("type") in PIN_TYPES]
    rest = sorted((s for s in meta if s not in pinned), key=score, reverse=True)

    def line(stem: str) -> str:
        d = meta[stem].get("hook") or meta[stem].get("description") or meta[stem].get("name") or stem
        d = re.sub(r"\s+", " ", d).strip().rstrip(".")
        if len(d) > HOOK_LEN:
            d = d[:HOOK_LEN - 1].rstrip() + "…"
        return f"- {stem} — {d}"

    header = HEADER.format(pins="/".join(sorted(PIN_TYPES)) or "pinned", b=BUDGET)
    out, used, kept = [header], len(header.encode()), []
    for s in pinned + rest:
        ln = line(s) + "\n"
        b = len(ln.encode())
        if s not in pinned and used + b > BUDGET - TRAILER_RESERVE:
            continue
        out.append(ln)
        used += b
        kept.append(s)
    dropped = [s for s in pinned + rest if s not in kept]

    # Below the fold: names only, wrapped so no line trips the validator's line
    # gate, and capped so the reserve is honoured. The budget goes to hot lines
    # (context), not to a complete roll-call of cold names, which the recall
    # hook serves anyway.
    if dropped:
        lines, cur = [], ""
        for w in dropped:
            if len(cur) + len(w) + 3 > 200:
                lines.append(cur)
                cur = w
            else:
                cur = f"{cur} · {w}" if cur else w
        if cur:
            lines.append(cur)
        body, shown = [], 0
        for l in lines:
            if len("\n".join(body + [l]).encode()) > TRAILER_RESERVE - 120:
                break
            body.append(l)
            shown += l.count(" · ") + 1
        more = len(dropped) - shown
        tail = f"\n*… and {more} more, retrieved per-prompt by the recall hook.*" if more > 0 else ""
        out.append("\n*Retrievable by recall, not always-loaded (%d):* \n" % len(dropped)
                   + "\n".join(body) + tail + "\n")
    text = "".join(out)

    coverage = sum(recalls.get(s, 0) for s in kept) / max(1, sum(recalls.values()))
    print(f"[{cfg.os_name()}] {len(meta)} active memories · {len(pinned)} pinned · "
          f"{len(kept)} on the page ({len(text.encode()):,}B) · {len(dropped)} below the fold · "
          f"page covers {100 * coverage:.0f}% of 30d recalls")

    if APPLY:
        archive = MEM / "archive"
        archive.mkdir(exist_ok=True)
        index = MEM / "MEMORY.md"
        if index.exists():
            backup = archive / f"MEMORY.md.{time.strftime('%Y%m%d-%H%M')}"
            backup.write_text(index.read_text(encoding="utf-8"), encoding="utf-8")
            print(f"previous page backed up to {backup}")
        index.write_text(text, encoding="utf-8")
        print("APPLIED")
    else:
        preview = cfg.cache_dir() / "memory-index-preview.md"
        preview.parent.mkdir(parents=True, exist_ok=True)
        preview.write_text(text, encoding="utf-8")
        print(f"dry run — preview at {preview}")
        print("\nTOP 12 by score:")
        for s in (pinned + rest)[:12]:
            print(f"  {score(s):7.1f}  {s}  (recalls {recalls.get(s, 0)}, in-links {indeg[s]})")
        print(f"\nBELOW THE FOLD (first 20 of {len(dropped)}):")
        for s in dropped[:20]:
            print(f"  {score(s):7.1f}  {s}  (recalls {recalls.get(s, 0)}, in-links {indeg[s]})")


if __name__ == "__main__":
    main()
